preprocess:
  input: data/raw/steel_energy_modified.csv
  output: data/processed/steel_energy_modified_clean.csv

split:
  method: time
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 400
  random_state: 42
  log1p_target: True

train:
  data: data/raw/steel_energy_modified_clean.csv
  model: models/model.pkl